[package]
name = "tm"
version = "0.1.0"
edition = "2021"

[features]
default = ["wbctl"]
wbctl = ["runtime-tinystm/wbctl"]
wbetl = ["runtime-tinystm/wbetl"]
wt    = ["runtime-tinystm/wt"]
norec = ["runtime-norec"]
tl2   = ["runtime-tl2"]
swisstm = ["runtime-swisstm"]
dudetm  = ["runtime-dudetm"]
tsxsgl  = ["runtime-tsxsgl"]
nvhtm   = ["runtime-nvhtm"]
spht    = ["runtime-spht"]
leftright = ["runtime-leftright"]
leftright-single = ["runtime-leftright-single"]
romulus   = ["runtime-romulus"]
xtm       = ["runtime-xtm"]
sgl-persistent  = ["runtime-sgl-persistent"]
sgl-distributed = ["runtime-sgl-distributed"]
tikv = ["runtime-tikv"]
mvlog = ["runtime-mvlog"]

[dependencies]
addrspace = { path = "../addrspace" }
runtime-core = { path = "../runtime/core" }
runtime-tinystm = { path = "../runtime/tinystm", default-features = false }
runtime-norec   = { path = "../runtime/norec", optional = true }
runtime-tl2     = { path = "../runtime/tl2", optional = true }
runtime-swisstm = { path = "../runtime/swisstm", optional = true }
runtime-dudetm  = { path = "../runtime/dudetm", optional = true }
runtime-tsxsgl  = { path = "../runtime/tsxsgl", optional = true }
runtime-nvhtm   = { path = "../runtime/nvhtm", optional = true }
runtime-spht    = { path = "../runtime/spht", optional = true }
runtime-leftright = { path = "../runtime/leftright", optional = true }
runtime-leftright-single = { path = "../runtime/leftright_single", optional = true }
runtime-romulus   = { path = "../runtime/romulus", optional = true }
runtime-xtm       = { path = "../runtime/xtm", optional = true }
runtime-sgl-persistent  = { path = "../runtime/sgl-persistent", optional = true }
runtime-sgl-distributed = { path = "../runtime/sgl-distributed", optional = true }
runtime-tikv = { path = "../runtime/tikv", optional = true }
runtime-mvlog = { path = "../runtime/mvlog", optional = true }
