[package]
name = "runtime-tinystm"
version = "0.1.0"
edition = "2021"

[dependencies]
addrspace = { path = "../../addrspace" }
runtime-core = { path = "../core" }
serde = { version = "1", features = ["derive", "alloc"], optional = true }

[features]
default = []
wbctl = []
wbetl = []
wt = []
simulation = ["runtime-core/simulation"]
stats = ["runtime-core/stats"]
serde = ["dep:serde", "runtime-core/serde"]
