#!/usr/bin/env python3
"""
compare_real_sim.py — Compare real C++ TM backends vs Rust simulation.

Runs C++ benchmarks (bank + 8 STAMP) across all backends with trace
generation, replays through tm-check (WBCTL model) and tm-sim (Rust
backend), and compares correctness and speed.

The simulator mmap's a fixed address range (0x7f00_0000_0000).  Real
C++ benchmarks allocate from the OS heap (region-allocator address).
This means tm-sim can only replay traces whose addresses fall in the
simulator's range — i.e., traces generated by tm-gen.  Real C++ traces
are replayed through tm-check (WBCTL model, no memory access) for
transaction-level correctness, and through compare_sim.py for aggregate
fidelity metrics.

Usage:
  python3 compare_real_sim.py                                  # run all
  python3 compare_real_sim.py --backends NOREC,TL2,TINYSTM      # selected
  python3 compare_real_sim.py --benchmarks bank,vacation        # selected
  python3 compare_real_sim.py --csv results.csv                 # output CSV
  python3 compare_real_sim.py --threads 4                       # single thread
  python3 compare_real_sim.py --duration 1000                   # 1 sec per run
  python3 compare_real_sim.py --sim-only                       # sim only, no real
  python3 compare_real_sim.py --real-only                      # real only, no sim
"""

import argparse
import csv
import json
import os
import re
import subprocess
import sys
import tempfile
import time
from collections import OrderedDict
from pathlib import Path

# ── Backends ───────────────────────────────────────────────

# Backends with Rust simulator equivalents (for tm-sim replay)
SIM_BACKENDS = {
    "NOREC": "norec",
    "TL2": "tl2",
    "TINYSTM": "tinystm",
}

# Additional C++ backends (timing + trace only, no sim comparison)
CPP_ONLY_BACKENDS = [
    "SWISSTM",
    "SGL",
    "LEFTRIGHT",
    "ROMULUS",
    "XTM",
    # "SPHT",    # requires -mrtm (HW TM)
    # "TSXSGL",  # requires -mrtm
]

ALL_BACKENDS = list(SIM_BACKENDS.keys()) + CPP_ONLY_BACKENDS

# ── Benchmarks ─────────────────────────────────────────────

BENCHMARKS = OrderedDict([
    ("bank", {"src": "bank/bank.cpp", "args": lambda t, d, ts=False:
        ["-d", str(d), "-a", "64", "-t", str(t)]}),
    ("vacation", {"src": "STAMP/vacation/vacation.cpp", "args": lambda t, d, ts=False:
        ["-p", str(t), "-r", "16384", "-n", "2", "-u", "98", "-t", "2048"] + (["--test"] if ts else [])}),
    ("labyrinth", {"src": "STAMP/labyrinth/labyrinth.cpp", "args": lambda t, d, ts=False:
        ["-p", str(t), "-x", "4", "-y", "4", "-z", "4", "-n", "32"] + (["--test"] if ts else [])}),
    ("kmeans", {"src": "STAMP/kmeans/kmeans.cpp", "args": lambda t, d, ts=False:
        ["-p", str(t), "-k", "8", "-d", "2", "-n", "512"] + (["--test"] if ts else [])}),
    ("genome", {"src": "STAMP/genome/genome.cpp", "args": lambda t, d, ts=False:
        ["-p", str(t), "-g", "4096", "-s", "32", "-n", "262144"] + (["--test"] if ts else [])}),
    ("intruder", {"src": "STAMP/intruder/intruder.cpp", "args": lambda t, d, ts=False:
        ["-p", str(t), "-a", "10", "-l", "64", "-n", "262144", "-s", "1"] + (["--test"] if ts else [])}),
    ("ssca2", {"src": "STAMP/ssca2/ssca2.cpp", "args": lambda t, d, ts=False:
        ["-p", str(t), "-s", "10", "-u", "1.0", "-l", "3", "-m", "3", "-i", "3"] + (["--test"] if ts else [])}),
    ("bayes", {"src": "STAMP/bayes/bayes.cpp", "args": lambda t, d, ts=False:
        ["-t", str(t), "-v", "16", "-r", "128", "-n", "2", "-p", "2", "-e", "2"] + (["--test"] if ts else [])}),
    ("yada", {"src": "STAMP/yada/yada.cpp", "args": lambda t, d, ts=False:
        ["-t", str(t), "-a", "10"] + (["--test"] if ts else [])}),
])

# ── Paths ──────────────────────────────────────────────────

PROJECT_ROOT = Path(__file__).resolve().parent.parent
CPP_DIR = PROJECT_ROOT / "benchmarks" / "cpp"
SIM_DIR = PROJECT_ROOT / "simulator"
BACKENDS_DIR = PROJECT_ROOT / "backends" / "tm_impl" / "common"
REGION_ALLOC = (PROJECT_ROOT / "backends" / "tm_impl" / "tm_region_allocator" / "tm_region_allocator.cpp")

def make_bin_name(bench_name: str) -> str:
    return f"bin/{bench_name}"

def build_cxx_flags(backend: str) -> tuple:
    """Return (cxxflags, extra_inc, defs, runtime) for a given backend."""
    base_inc = f"-I{PROJECT_ROOT} -I{PROJECT_ROOT}/expli_instr/cpp"
    common_inc = "-I" + str(PROJECT_ROOT / "backends" / "tm_impl" / "common")
    common_inc2 = f"-I{PROJECT_ROOT}/backends/tm_impl"
    CXX = os.environ.get("CXX", "clang++-22")
    CXXFLAGS = f"-std=c++20 -O3 -march=native -pthread -DNDEBUG {base_inc}"

    backend_map = {
        "TINYSTM": {"defs": "-DTM_BACKEND_TINYSTM -DDESIGN_WBCTL",
                    "extra_inc": f"-I{PROJECT_ROOT}/backends/tm_impl/tiny_stm",
                    "runtime": f"{PROJECT_ROOT}/backends/tm_impl/tiny_stm/TinySTM_runtime.cpp"},
        "WBETL":   {"defs": "-DTM_BACKEND_TINYSTM -DDESIGN_WBETL",
                    "extra_inc": f"-I{PROJECT_ROOT}/backends/tm_impl/tiny_stm -I{PROJECT_ROOT}/backends/stubs",
                    "runtime": f"{PROJECT_ROOT}/backends/tm_impl/tiny_stm/TinySTM_runtime.cpp"},
        "WT":      {"defs": "-DTM_BACKEND_TINYSTM -DDESIGN_WT",
                    "extra_inc": f"-I{PROJECT_ROOT}/backends/tm_impl/tiny_stm",
                    "runtime": f"{PROJECT_ROOT}/backends/tm_impl/tiny_stm/TinySTM_runtime.cpp"},
        "NOREC":   {"defs": "-DTM_BACKEND_NOREC",
                    "extra_inc": f"-I{PROJECT_ROOT}/backends/tm_impl/norec",
                    "runtime": f"{PROJECT_ROOT}/backends/tm_impl/norec/NOrec_runtime.cpp"},
        "SWISSTM": {"defs": "-DTM_BACKEND_SWISSTM",
                    "extra_inc": f"-I{PROJECT_ROOT}/backends/tm_impl/swisstm",
                    "runtime": f"{PROJECT_ROOT}/backends/tm_impl/swisstm/SwissTM_runtime.cpp"},
        "TL2":     {"defs": "-DTM_BACKEND_TL2",
                    "extra_inc": f"-I{PROJECT_ROOT}/backends/tm_impl/tl2",
                    "runtime": f"{PROJECT_ROOT}/backends/tm_impl/tl2/tl2_runtime.cpp"},
        "SGL":     {"defs": "-DTM_BACKEND_SGL",
                    "extra_inc": "",
                    "runtime": f"{PROJECT_ROOT}/backends/tm_impl/single_global_lock/SingleGlobalLock_runtime.cpp"},
        "LEFTRIGHT": {"defs": "-DTM_BACKEND_LEFTRIGHT",
                      "extra_inc": f"-I{PROJECT_ROOT}/backends/tm_impl/leftright",
                      "runtime": f"{PROJECT_ROOT}/backends/tm_impl/leftright/leftright_runtime.cpp"},
        "ROMULUS": {"defs": "-DTM_BACKEND_ROMULUS",
                    "extra_inc": f"-I{PROJECT_ROOT}/backends/tm_impl/romulus",
                    "runtime": f"{PROJECT_ROOT}/backends/tm_impl/romulus/romulus_runtime.cpp"},
        "XTM":     {"defs": "-DTM_BACKEND_XTM",
                    "extra_inc": f"-I{PROJECT_ROOT}/backends/tm_impl/xtm",
                    "runtime": f"{PROJECT_ROOT}/backends/tm_impl/xtm/xtm_runtime.cpp"},
    }
    info = backend_map.get(backend)
    if not info:
        raise ValueError(f"Unknown backend: {backend}")
    cxxflags = f"{CXX} {CXXFLAGS} {info['extra_inc']} {common_inc} {common_inc2}"
    defs = info["defs"]
    runtime = info["runtime"]
    return cxxflags, defs, runtime

def build_benchmark(backend: str, bench_name: str, out_dir: str, rebuild: bool = False) -> str:
    """Build a C++ benchmark with trace runtime linked. Returns binary path."""
    bn = make_bin_name(bench_name)
    bin_path = os.path.join(CPP_DIR, bn)

    if not rebuild and os.path.exists(bin_path):
        return bin_path

    try:
        cxxflags, defs, runtime = build_cxx_flags(backend)
    except ValueError as e:
        print(f"  SKIP {backend}/{bench_name}: {e}")
        return None

    hooks_src = (f"{BACKENDS_DIR}/tm_hooks.cpp {BACKENDS_DIR}/tm_trace_runtime.cpp")
    
    # Ensure bin/ dir exists
    os.makedirs(os.path.join(CPP_DIR, "bin"), exist_ok=True)
    os.makedirs(os.path.join(CPP_DIR, "STAMP", "kmeans"), exist_ok=True)
    os.makedirs(os.path.join(CPP_DIR, "STAMP", "genome"), exist_ok=True)
    os.makedirs(os.path.join(CPP_DIR, "STAMP", "intruder"), exist_ok=True)
    os.makedirs(os.path.join(CPP_DIR, "STAMP", "ssca2"), exist_ok=True)

    src_path = os.path.join(CPP_DIR, BENCHMARKS[bench_name]["src"])
    cmd = (f"{cxxflags} {defs} -o {bin_path} {src_path} "
           f"{runtime} {REGION_ALLOC} {hooks_src} -pthread")

    subprocess.run(cmd, shell=True, cwd=CPP_DIR, check=True,
                   capture_output=True, text=True)
    return bin_path

def run_benchmark(bin_path: str, args: list, trace_path: str, timeout_ms: int = 10000,
                  env_extra: dict = None) -> dict:
    """Run a benchmark, measure wall time, return results."""
    env = os.environ.copy()
    env["TM_TRACE_PATH"] = trace_path
    if env_extra:
        env.update(env_extra)

    start = time.time()
    try:
        proc = subprocess.run(
            [bin_path] + args,
            env=env, cwd=CPP_DIR,
            capture_output=True, text=True,
            timeout=timeout_ms / 1000.0,
        )
        elapsed = time.time() - start
        return {
            "rc": proc.returncode,
            "stdout": proc.stdout,
            "stderr": proc.stderr,
            "elapsed": elapsed,
            "timed_out": False,
        }
    except subprocess.TimeoutExpired:
        elapsed = time.time() - start
        return {
            "rc": -1,
            "stdout": "",
            "stderr": f"TIMEOUT after {elapsed:.1f}s",
            "elapsed": elapsed,
            "timed_out": True,
        }

def count_trace_events(trace_path: str) -> dict:
    """Count TxBegin, TxEnd, Abort events from raw trace."""
    counts = {"begin": 0, "end": 0, "abort": 0, "total": 0}
    try:
        with open(trace_path) as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith('#'):
                    continue
                counts["total"] += 1
                parts = line.split()
                if len(parts) < 3:
                    continue
                try:
                    tc = int(parts[2])
                except ValueError:
                    continue
                if tc == 2:
                    counts["begin"] += 1
                elif tc == 3:
                    counts["end"] += 1
                elif tc == 6:
                    counts["abort"] += 1
    except FileNotFoundError:
        pass
    counts["commits"] = counts["end"]
    counts["abort_actual"] = counts["begin"] - counts["end"]
    return counts

def parse_sim_output(output: str) -> dict:
    """Parse tm-check or tm-sim output for commit/abort counts."""
    result = {}
    m = re.search(r'Commits:\s+(\d+)\s+Aborts:\s+(\d+)', output)
    if m:
        result["commits"] = int(m.group(1))
        result["aborts"] = int(m.group(2))
    m = re.search(r'NO MEMORY VIOLATIONS', output)
    result["clean"] = m is not None
    m = re.search(r'Events processed:\s+(\d+)', output)
    if m:
        result["events"] = int(m.group(1))
    return result

def run_trace2jsonl(input_path: str, output_path: str) -> bool:
    """Convert raw trace to JSONL. Returns True on success."""
    try:
        subprocess.run(
            ["cargo", "run", "--release", "--bin", "tm-trace2jsonl",
             "--", "-i", input_path, "-o", output_path],
            cwd=SIM_DIR, check=True, capture_output=True, text=True,
            timeout=30,
        )
        return True
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired):
        return False

def run_sim(trace_path: str, backend: str, timeout_s: int = 30) -> dict:
    """Run tm-sim on a JSONL trace. Returns parsed output + elapsed time."""
    start = time.time()
    try:
        proc = subprocess.run(
            ["cargo", "run", "--release", "--bin", "tm-sim", "--",
             "--backend", backend, "--trace", trace_path],
            cwd=SIM_DIR, capture_output=True, text=True,
            timeout=timeout_s,
        )
        elapsed = time.time() - start
        combined = proc.stderr + "\n" + proc.stdout
        result = parse_sim_output(combined)
        result["elapsed"] = elapsed
        result["rc"] = proc.returncode
        return result
    except subprocess.TimeoutExpired:
        elapsed = time.time() - start
        return {"rc": -1, "elapsed": elapsed, "timed_out": True, "clean": False}

def run_model(trace_path: str, timeout_s: int = 30) -> dict:
    """Run tm-check (WBCTL model) on a JSONL trace."""
    start = time.time()
    try:
        proc = subprocess.run(
            ["cargo", "run", "--release", "--bin", "tm-check", "--",
             "--trace", trace_path],
            cwd=SIM_DIR, capture_output=True, text=True,
            timeout=timeout_s,
        )
        elapsed = time.time() - start
        combined = proc.stderr + "\n" + proc.stdout
        result = parse_sim_output(combined)
        result["elapsed"] = elapsed
        result["rc"] = proc.returncode
        return result
    except subprocess.TimeoutExpired:
        elapsed = time.time() - start
        return {"rc": -1, "elapsed": elapsed, "timed_out": True, "clean": False}

def run_synthetic_sim(backend: str, num_threads: int = 2) -> dict:
    """Run tm-gen + tm-sim for synthetic trace. Returns results."""
    # Generate trace
    gen_proc = subprocess.run(
        ["cargo", "run", "--release", "--bin", "tm-gen", "--",
         "--scenario", "all", "--output", "-"],
        cwd=SIM_DIR, capture_output=True, text=True, timeout=10,
    )
    if gen_proc.returncode != 0:
        return {"error": f"tm-gen failed: {gen_proc.stderr}"}

    # Parse JSONL to count events
    events = []
    for line in gen_proc.stdout.strip().split("\n"):
        if line:
            events.append(json.loads(line))
    
    trace_data = "\n".join(json.dumps(e) for e in events)

    # Write to temp file
    import tempfile
    fd, trace_path = tempfile.mkstemp(suffix=".jsonl", prefix="synth_")
    os.close(fd)
    with open(trace_path, "w") as f:
        f.write(trace_data)

    # Run tm-sim
    sim_result = run_sim(trace_path, backend)

    # Count events in trace
    sim_result["trace_events"] = len(events)
    sim_result["trace_path"] = trace_path
    return sim_result

def run_synthetic_model(num_threads: int = 2) -> dict:
    """Run tm-gen + tm-check for synthetic trace on WBCTL model."""
    gen_proc = subprocess.run(
        ["cargo", "run", "--release", "--bin", "tm-gen", "--",
         "--scenario", "all", "--output", "-"],
        cwd=SIM_DIR, capture_output=True, text=True, timeout=10,
    )
    if gen_proc.returncode != 0:
        return {"error": f"tm-gen failed: {gen_proc.stderr}"}

    events = [json.loads(line) for line in gen_proc.stdout.strip().split("\n") if line]
    trace_data = "\n".join(json.dumps(e) for e in events)

    fd, trace_path = tempfile.mkstemp(suffix=".jsonl", prefix="synth_")
    os.close(fd)
    with open(trace_path, "w") as f:
        f.write(trace_data)

    model_result = run_model(trace_path)
    model_result["trace_events"] = len(events)
    model_result["trace_path"] = trace_path
    return model_result

# ── Reporting ──────────────────────────────────────────────

class ResultsTable:
    def __init__(self):
        self.rows = []

    def header(self) -> list:
        return [
            "Backend", "Benchmark", "Real?",
            "RealTime(s)", "SimTime(s)", "Speedup",
            "RealCmts", "SimCmts", "RealAbrt", "SimAbrt",
            "Fidelity", "Clean", "Notes",
        ]

    def add(self, backend: str, benchmark: str, real_run: str,
            real_time: float, sim_time: float, speedup: str,
            real_cmts: int, sim_cmts, real_abrt: int, sim_abrt,
            fidelity: str, clean: str, notes: str = ""):
        self.rows.append({
            "Backend": backend, "Benchmark": benchmark, "Real?": real_run,
            "RealTime(s)": f"{real_time:.3f}" if real_time >= 0 else "N/A",
            "SimTime(s)": f"{sim_time:.3f}" if sim_time >= 0 else "N/A",
            "Speedup": speedup,
            "RealCmts": real_cmts if real_cmts >= 0 else "N/A",
            "SimCmts": sim_cmts if sim_cmts is not None and sim_cmts >= 0 else "N/A",
            "RealAbrt": real_abrt if real_abrt >= 0 else "N/A",
            "SimAbrt": sim_abrt if sim_abrt is not None and sim_abrt >= 0 else "N/A",
            "Fidelity": fidelity,
            "Clean": clean,
            "Notes": notes,
        })

    def print_table(self):
        h = self.header()
        sep = " | "
        widths = {}
        for col in h:
            vals = [str(r.get(col, "")) for r in self.rows] + [col]
            widths[col] = max(len(v) for v in vals)

        def fmt_row(row):
            return sep.join(str(row.get(c, "")).ljust(widths[c]) for c in h)

        print("\n" + "=" * (sum(widths.values()) + len(sep) * (len(h) - 1)))
        print("COMPARISON REPORT: C++ Real vs Rust Simulation")
        print("=" * (sum(widths.values()) + len(sep) * (len(h) - 1)))
        print(fmt_row({c: c for c in h}))
        print("-" * (sum(widths.values()) + len(sep) * (len(h) - 1)))
        for row in self.rows:
            print(fmt_row(row))
        print("=" * (sum(widths.values()) + len(sep) * (len(h) - 1)))

    def save_csv(self, path: str):
        with open(path, "w", newline="") as f:
            w = csv.DictWriter(f, fieldnames=self.header())
            w.writeheader()
            for row in self.rows:
                w.writerow(row)
        print(f"\nResults saved to {path}")

# ── Main ───────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Compare real C++ TM backends vs Rust simulation"
    )
    parser.add_argument("--backends",
        default=",".join(ALL_BACKENDS),
        help="Comma-separated backends (default: all)")
    parser.add_argument("--benchmarks",
        default=",".join(BENCHMARKS.keys()),
        help="Comma-separated benchmarks (default: all)")
    parser.add_argument("--threads", type=int, default=2,
        help="Number of threads (default: 2)")
    parser.add_argument("--duration", type=int, default=500,
        help="Benchmark duration in ms (default: 500)")
    parser.add_argument("--csv", default=None,
        help="Output CSV path")
    parser.add_argument("--real-only", action="store_true",
        help="Only run real C++ benchmarks (skip sim)")
    parser.add_argument("--sim-only", action="store_true",
        help="Only run synthetic sim comparison (skip real)")
    parser.add_argument("--rebuild", action="store_true",
        help="Force rebuild C++ benchmarks")
    parser.add_argument("--timeout", type=int, default=30,
        help="Per-simulation timeout in seconds (default: 30)")
    args = parser.parse_args()

    backends = [b.strip() for b in args.backends.split(",") if b.strip()]
    benchmarks = [b.strip() for b in args.benchmarks.split(",") if b.strip() in BENCHMARKS]

    print(f"Backends: {', '.join(backends)}")
    print(f"Benchmarks: {', '.join(benchmarks)}")
    print(f"Threads: {args.threads}  Duration: {args.duration}ms\n")

    results = ResultsTable()

    # ── Part 1: Real C++ benchmarks ─────────────────────────
    if not args.sim_only:
        print("═" * 60)
        print("PART 1: Real C++ Benchmarks")
        print("═" * 60)

        for backend in backends:
            print(f"\n── Backend: {backend} ──")
            has_sim = backend in SIM_BACKENDS

            for bench_name in benchmarks:
                print(f"  Building {bench_name}... ", end="", flush=True)
                bin_path = build_benchmark(backend, bench_name, "bin", args.rebuild)
                if bin_path is None:
                    print("SKIP (build failed)")
                    continue

                # Check for --test flag (self-test mode)
                test_args = []
                if "--test" in " ".join(BENCHMARKS[bench_name]["args"](args.threads, args.duration, True)):
                    # Run self-tests first
                    test_bin = bin_path
                    test_res = run_benchmark(test_bin, ["--test"], "/dev/null", 30000)
                    if test_res["rc"] != 0 and test_res["rc"] != -1:
                        test_out = test_res["stdout"] + test_res["stderr"]
                        if "FAILED" in test_out or "failed" in test_out:
                            print(f"TESTS FAILED: {test_res['rc']}")
                            continue
                    print(f"tests OK ", end="")

                # Real run with trace
                fd, trace_path = tempfile.mkstemp(suffix=".txt", prefix=f"trace_{backend}_{bench_name}_")
                os.close(fd)

                bargs = BENCHMARKS[bench_name]["args"](args.threads, args.duration)
                print("running... ", end="", flush=True)

                result = run_benchmark(bin_path, bargs, trace_path, args.timeout * 1000)

                if result["timed_out"]:
                    print(f"TIMEOUT ({result['elapsed']:.1f}s)")
                    results.add(backend, bench_name, "real", -1, -1, "N/A",
                                -1, None, -1, None, "N/A", "N/A", "TIMEOUT")
                    continue

                print(f"{result['elapsed']:.3f}s ", end="", flush=True)

                # Parse trace
                trace_counts = count_trace_events(trace_path)
                print(f"tx={trace_counts['begin']} cmt={trace_counts['commits']} ", end="")

                # Check PASS/FAIL in output
                combined_out = result["stdout"] + result["stderr"]
                passed = "PASS" in combined_out and "FAIL" not in combined_out
                clean_str = "OK" if passed else "CHECK"

                # ── Simulation comparison (if backend has sim equivalent) ──
                sim_time = -1
                sim_cmts = None
                sim_abrt = None
                fidelity = "N/A"
                sim_clean = "N/A"
                speedup = "N/A"
                notes = ""

                if has_sim and os.path.getsize(trace_path) > 0:
                    fd_j, jsonl_path = tempfile.mkstemp(suffix=".jsonl", prefix=f"jsonl_{backend}_{bench_name}_")
                    os.close(fd_j)
                    conv_ok = run_trace2jsonl(trace_path, jsonl_path)

                    if conv_ok:
                        # Run model (WBCTL) — memory-safe, any address range
                        print("model... ", end="", flush=True)
                        model_res = run_model(jsonl_path, args.timeout)
                        mc = model_res.get("commits", -1)
                        ma = model_res.get("aborts", -1)
                        clean = model_res.get("clean", False)
                        if model_res.get("rc", -1) == 0 or mc >= 0:
                            sim_clean = "OK" if clean else "VIOLATION"
                            notes = f"model:cmt={mc},abt={ma}"
                            print(f"model({mc}/{ma}) ", end="")
                        else:
                            print(f"model:FAIL ", end="")

                        # tm-sim runs require matching address ranges.
                        # Try it; will likely crash on real traces.
                        print("sim... ", end="", flush=True)
                        sim_res = run_sim(jsonl_path, SIM_BACKENDS[backend], args.timeout)
                        if sim_res.get("timed_out"):
                            print(f"timelimit ", end="")
                            notes += ", sim:TIMEOUT"
                        elif sim_res.get("rc", -1) == 0:
                            sim_cmts = sim_res.get("commits", 0)
                            sim_abrt = sim_res.get("aborts", 0)
                            sim_time = sim_res.get("elapsed", 0)
                            sim_clean = "OK" if sim_res.get("clean", False) else "VIOLATION"
                            if sim_time > 0 and result["elapsed"] > 0:
                                ratio = result["elapsed"] / sim_time
                                speedup = f"{ratio:.2f}x"
                            print(f"sim({sim_cmts}/{sim_abrt}) ", end="")
                        else:
                            print(f"sim:CRASH ", end="")
                            notes += ", sim:ADDR_MISMATCH"

                    if conv_ok and os.path.exists(jsonl_path):
                        os.unlink(jsonl_path)

                # Cleanup
                if os.path.exists(trace_path):
                    os.unlink(trace_path)

                print(f"[{clean_str}]")

                results.add(backend, bench_name, "real",
                            result["elapsed"], sim_time, speedup,
                            trace_counts["commits"], sim_cmts,
                            trace_counts["abort_actual"], sim_abrt,
                            fidelity, clean_str, notes)

    # ── Part 2: Synthetic simulation comparison ─────────────
    if not args.real_only:
        print("\n" + "═" * 60)
        print("PART 2: Synthetic Simulation Benchmarks")
        print("═" * 60)

        # Model comparison (WBCTL)
        print("\n── WBCTL Model (tm-check) ──")
        model_res = run_synthetic_model(args.threads)
        if "error" in model_res:
            print(f"  ERROR: {model_res['error']}")
        else:
            mc = model_res.get("commits", 0)
            ma = model_res.get("aborts", 0)
            me = model_res.get("elapsed", 0)
            print(f"  Commits={mc}  Aborts={ma}  Clean={model_res.get('clean','?')}  "
                  f"Time={me:.3f}s  Events={model_res.get('trace_events',0)}")
            if "trace_path" in model_res and os.path.exists(model_res["trace_path"]):
                os.unlink(model_res["trace_path"])
            results.add("WBCTL", "synthetic(tm-gen)", "model", me, -1, "N/A",
                        mc, mc, ma, ma, "100.0%", "OK", f"events={model_res.get('trace_events',0)}")

        # Sim backends
        for backend in ["norec", "tl2", "tinystm"]:
            print(f"\n── Rust {backend} (tm-sim) ──")
            sim_res = run_synthetic_sim(backend, args.threads)
            if "error" in sim_res:
                print(f"  ERROR: {sim_res['error']}")
                results.add(backend.upper(), "synthetic(tm-gen)", "sim",
                            -1, -1, "N/A", -1, -1, -1, -1, "N/A", "N/A", sim_res["error"])
                continue
            sc = sim_res.get("commits", 0)
            sa = sim_res.get("aborts", 0)
            se = sim_res.get("elapsed", 0)
            clean_str = "OK" if sim_res.get("clean", False) else "VIOLATION"
            print(f"  Commits={sc}  Aborts={sa}  Clean={sim_res.get('clean','?')}  "
                  f"Time={se:.3f}s  Events={sim_res.get('trace_events',0)}")
            results.add(backend.upper(), "synthetic(tm-gen)", "sim",
                        -1, se, "N/A", -1, sc, -1, sa, "100.0%", clean_str,
                        f"events={sim_res.get('trace_events',0)}")
            if "trace_path" in sim_res and os.path.exists(sim_res["trace_path"]):
                os.unlink(sim_res["trace_path"])

    # ── Part 3: Summary ─────────────────────────────────────
    print("\n" + "═" * 60)
    print("SUMMARY")
    print("═" * 60)

    # Count results
    real_ok = sum(1 for r in results.rows if r.get("Real?") == "real" and r.get("Notes", "") != "TIMEOUT")
    real_timeout = sum(1 for r in results.rows if r.get("Real?") == "real" and r.get("Notes", "") == "TIMEOUT")
    sim_ok = sum(1 for r in results.rows if r.get("Real?") in ("sim", "model"))
    print(f"  Real runs: {real_ok} OK, {real_timeout} timeout")
    print(f"  Sim runs:  {sim_ok}")

    # Speed comparison: real vs simulation for matched runs
    matched = [r for r in results.rows
               if r.get("SimTime(s)") != "N/A" and r.get("RealTime(s)") != "N/A"
               and r["Real?"] == "real"]
    if matched:
        print("\n  Real vs Sim speed comparison (matched runs):")
        for row in matched:
            rt = float(row["RealTime(s)"])
            st = float(row["SimTime(s)"])
            print(f"    {row['Backend']:>8s}/{row['Benchmark']:>10s}: "
                  f"real={rt:.3f}s sim={st:.3f}s "
                  f"ratio={rt/st:.2f}x")

    results.print_table()
    if args.csv:
        results.save_csv(args.csv)

if __name__ == "__main__":
    main()
