#include <atomic>
#include <cassert>
#include <csetjmp>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <map>

#define TM_BUFFER_SIZE 1024

// Forward declarations of symbol tables (generated by the plugin)
extern const char *tm_symbol_names[];
extern const void *tm_symbol_addresses[];
extern const uint32_t tm_symbol_count;

// index to get the symbol_id
static std::map<void *, uint32_t> *tm_addr_symbol_map = nullptr;

extern "C" {
// Helper function to get symbol name
static const char *tm_get_symbol_name(uint32_t symbol_id)
{
	if (symbol_id == 0xFFFFFFFF || symbol_id >= tm_symbol_count) {
		return "<unknown>";
	}
	return tm_symbol_names[symbol_id];
}

static const char *tm_get_symbol_name_from_addr(void *addr)
{
	auto it = tm_addr_symbol_map->find(addr);
	uint32_t symbol_id = 0xFFFFFFFF;
	if (it != tm_addr_symbol_map->end())
		symbol_id = it->second;
	return tm_get_symbol_name(symbol_id);
}

// Helper function to get symbol type string
static const char *tm_get_type_string(uint8_t type)
{
	switch (type) {
	case 1:
		return "i8";
	case 2:
		return "i16";
	case 3:
		return "i32";
	case 4:
		return "i64";
	case 5:
		return "f32";
	case 6:
		return "f64";
	case 7:
		return "ptr";
	default:
		return "unknown";
	}
}

// __thread vs thread_local: inspecting llvm ir, thread_local is
// marked as internal, hence we need to use __thread for the
// injected variables to be globaly accessible

__thread unsigned char tm_jmpbuf[256];
__thread int32_t tm_nested_call_counter;
__thread int32_t tm_longjmp_ret;
__thread uint8_t is_tm_init_thread_ready = 0;
thread_local uint8_t tm_buffer[TM_BUFFER_SIZE] = {0};

std::atomic<int8_t> tm_is_init_ready{0};

void tm_init()
{
	printf("tm_init\n");
	fflush(stdout);
	tm_addr_symbol_map = new std::map<void *, uint32_t>();
	for (uint32_t i = 0; i < tm_symbol_count; ++i) {
		void *addr = (void *)tm_symbol_addresses[i];
		tm_addr_symbol_map->insert(std::pair(addr, i));
		printf("SYMBOL %s addr %p\n", tm_get_symbol_name(i), addr);
	}
	tm_is_init_ready.store(1);
}

void tm_exit()
{
	tm_is_init_ready.store(0);
	delete tm_addr_symbol_map;
	printf("tm_exit\n");
	fflush(stdout);
}

void tm_init_thread()
{
	if (is_tm_init_thread_ready == 0) {
		printf("tm_init_thread\n");
		fflush(stdout);
		is_tm_init_thread_ready = 1;
	}
}

void tm_exit_thread()
{
	if (is_tm_init_thread_ready == 1) {
		printf("tm_exit_thread\n");
		fflush(stdout);
		is_tm_init_thread_ready = 0;
	}
}

void tm_begin()
{
	printf("tm_nested_call_counter=%d  --  ", tm_nested_call_counter);
	if (tm_nested_call_counter == 1) {
		printf("tm_begin outer\n");
	} else {
		printf("tm_begin nested %d\n", tm_nested_call_counter);
	}
}

void tm_end()
{
	printf("tm_nested_call_counter=%d  --  ", tm_nested_call_counter);
	if (tm_nested_call_counter == 1) {
		printf("tm_end outer\n");
	} else {
		printf("tm_end nested %d\n", tm_nested_call_counter);
	}
}

// sigsetjmp/longjmp implementation
int tm_setjmp() { return sigsetjmp(*(sigjmp_buf *)tm_jmpbuf, 0); }

void tm_longjmp(int val) { longjmp(*(sigjmp_buf *)tm_jmpbuf, val); }

// int tm_setjmp() { return sigsetjmp(*(sigjmp_buf *)tm_jmpbuf, 0); }

int8_t tm_read_i1(void *addr)
{
	int8_t val = *(int8_t *)addr;
	printf("tm_read_i1\n");
	return val;
}

int16_t tm_read_i2(void *addr)
{
	int16_t val = *(int16_t *)addr;
	printf("tm_read_i2\n");
	return val;
}

int32_t tm_read_i4(void *addr)
{
	int32_t val = *(int32_t *)addr;
	printf("tm_read_i4 (%s %p --> %i)\n", tm_get_symbol_name_from_addr(addr), addr, val);
	return val;
}

int64_t tm_read_i8(void *addr)
{
	int64_t val = *(int64_t *)addr;
	printf("tm_read_i8\n");
	return val;
}

float tm_read_f4(void *addr)
{
	float val = *(float *)addr;
	printf("tm_read_f4\n");
	return val;
}

double tm_read_f8(void *addr)
{
	double val = *(double *)addr;
	printf("tm_read_f8\n");
	return val;
}

void *tm_read_ptr(void *addr)
{
	void *val = *(void **)addr;
	printf("tm_read_ptr\n");
	return val;
}

void *tm_read_z(void *src, size_t sz)
{
	assert(sz < TM_BUFFER_SIZE);
	memcpy(tm_buffer, src, sz);
	printf("tm_read_z\n");
	return tm_buffer;
}

void tm_write_i1(void *addr, uint8_t val)
{
	fflush(stdout);
	fprintf(stderr, "CALLING tm_write_i1\n");
	fflush(stderr);
	printf("tm_write_i1\n");
	fflush(stdout);
	*(uint8_t *)addr = val;
}

void tm_write_i2(void *addr, int16_t val)
{
	printf("tm_write_i2\n");
	*(int16_t *)addr = val;
}

void tm_write_i4(void *addr, int32_t val)
{
	printf("tm_write_i4 (%s %p <-- %i)\n", tm_get_symbol_name_from_addr(addr), addr, val);
	*(int32_t *)addr = val;
}

void tm_write_i8(void *addr, int64_t val)
{
	printf("tm_write_i8\n");
	*(int64_t *)addr = val;
}

void tm_write_f4(void *addr, float val)
{
	printf("tm_write_f4\n");
	*(float *)addr = val;
}

void tm_write_f8(void *addr, double val)
{
	printf("tm_write_f8\n");
	*(double *)addr = val;
}

void tm_write_ptr(void *addr, void *val)
{
	printf("tm_write_ptr\n");
	*(void **)addr = val;
}

void tm_write_z(void *dst, void *src, size_t sz)
{
	assert(sz < TM_BUFFER_SIZE);
	memcpy(dst, src, sz);
	printf("tm_write_z\n");
}

void tm_memset(void *dst, uint8_t value, size_t sz)
{
	assert(sz < TM_BUFFER_SIZE);
	memset(dst, value, sz);
	printf("tm_memset\n");
}

void consume_ptr(volatile void *ptr) { (void)ptr; }
}
