#include <cstdint>
#include <cstdio>
#include <cassert>
#include <cstring>
#include <csetjmp>
#include <atomic>

#define TM_BUFFER_SIZE 1024

// Symbol table structure matching what the LLVM pass generates
struct tm_symbol_entry {
    uint32_t id;
    const char* name;
    uint8_t type;
    void* address;
};

// Forward declarations of symbol tables (generated by the plugin)
extern "C" const char* tm_symbol_names[];
extern "C" const void* tm_symbol_addresses[];
extern "C" const uint32_t tm_symbol_count;

// Helper function to get symbol name
static const char* tm_get_symbol_name(uint32_t symbol_id) {
    if (symbol_id == 0xFFFFFFFF || symbol_id >= tm_symbol_count) {
        return "<unknown>";
    }
    return tm_symbol_names[symbol_id];
}

// Helper function to get symbol type string
static const char* tm_get_type_string(uint8_t type) {
    switch (type) {
        case 1: return "i8";
        case 2: return "i16";
        case 3: return "i32";
        case 4: return "i64";
        case 5: return "f32";
        case 6: return "f64";
        case 7: return "ptr";
        default: return "unknown";
    }
}

// __thread vs thread_local: inspecting llvm ir, thread_local is
// marked as internal, hence we need to use __thread for the
// injected variables to be globaly accessible

__thread unsigned char tm_jmpbuf[256];
__thread int32_t tm_nested_call_counter;
__thread int32_t tm_jmpbuf_ret;
__thread uint8_t is_tm_init_thread_ready = 0;
thread_local uint8_t tm_buffer[TM_BUFFER_SIZE] = {0};

std::atomic<int8_t> tm_is_init_ready{0};

extern "C" void tm_init() {
    printf("tm_init\n");
    fflush(stdout);
    tm_is_init_ready.store(1);
}

extern "C" void tm_exit() {
    tm_is_init_ready.store(0);
    printf("tm_exit\n");
    fflush(stdout);
}

extern "C" void tm_init_thread() {
    if (is_tm_init_thread_ready == 0) {
        printf("tm_init_thread\n");
        fflush(stdout);
        is_tm_init_thread_ready = 1;
    }
}

extern "C" void tm_exit_thread() {
    if (is_tm_init_thread_ready == 1) {
        printf("tm_exit_thread\n");
        fflush(stdout);
        is_tm_init_thread_ready = 0;
    }
}

extern "C" void tm_begin() {
    printf("tm_nested_call_counter=%d  --  ", tm_nested_call_counter);
    if (tm_nested_call_counter == 1) {
        printf("tm_begin outer\n");
    } else {
        printf("tm_begin nested %d\n", tm_nested_call_counter);
    }
}

extern "C" void tm_end() {
    printf("tm_nested_call_counter=%d  --  ", tm_nested_call_counter);
    if (tm_nested_call_counter == 1) {
        printf("tm_end outer\n");
    } else {
        printf("tm_end nested %d\n", tm_nested_call_counter);
    }
}

extern "C" int tm_setjmp() {
    return sigsetjmp(*(sigjmp_buf*)tm_jmpbuf, 0);
}

extern "C" int8_t tm_read_i1(void* addr, uint32_t symbol_id) {
    int8_t val = *(int8_t*)addr;
    printf("tm_read_i1(%s[%p]) = %d\n", tm_get_symbol_name(symbol_id), addr, val);
    return val;
}

extern "C" int16_t tm_read_i2(void* addr, uint32_t symbol_id) {
    int16_t val = *(int16_t*)addr;
    printf("tm_read_i2(%s[%p]) = %d\n", tm_get_symbol_name(symbol_id), addr, val);
    return val;
}

extern "C" int32_t tm_read_i4(void* addr, uint32_t symbol_id) {
    int32_t val = *(int32_t*)addr;
    printf("tm_read_i4(%s[%p]) = %d\n", tm_get_symbol_name(symbol_id), addr, val);
    return val;
}

extern "C" int64_t tm_read_i8(void* addr, uint32_t symbol_id) {
    int64_t val = *(int64_t*)addr;
    printf("tm_read_i8(%s[%p]) = %lld\n", tm_get_symbol_name(symbol_id), addr, val);
    return val;
}

extern "C" float tm_read_f4(void* addr, uint32_t symbol_id) {
    float val = *(float*)addr;
    printf("tm_read_f4(%s[%p]) = %f\n", tm_get_symbol_name(symbol_id), addr, val);
    return val;
}

extern "C" double tm_read_f8(void* addr, uint32_t symbol_id) {
    double val = *(double*)addr;
    printf("tm_read_f8(%s[%p]) = %lf\n", tm_get_symbol_name(symbol_id), addr, val);
    return val;
}

extern "C" void* tm_read_ptr(void* addr, uint32_t symbol_id) {
    void* val = *(void**)addr;
    printf("tm_read_ptr(%s[%p]) = %p\n", tm_get_symbol_name(symbol_id), addr, val);
    return val;
}

extern "C" void* tm_read_z(void* src, size_t sz, uint32_t symbol_id) {
    assert(sz < TM_BUFFER_SIZE);
    memcpy(tm_buffer, src, sz);
    printf("tm_read_z(%s[%p], %zu) = %p\n", tm_get_symbol_name(symbol_id), src, sz, (void*)tm_buffer);
    return tm_buffer;
}

extern "C" void tm_write_i1(void* addr, uint8_t val, uint32_t symbol_id) {
    printf("tm_write_i1(%s[%p], %u)\n", tm_get_symbol_name(symbol_id), addr, val);
    *(uint8_t*)addr = val;
}

extern "C" void tm_write_i2(void* addr, int16_t val, uint32_t symbol_id) {
    printf("tm_write_i2(%s[%p], %hd)\n", tm_get_symbol_name(symbol_id), addr, val);
    *(int16_t*)addr = val;
}

extern "C" void tm_write_i4(void* addr, int32_t val, uint32_t symbol_id) {
    printf("tm_write_i4(%s[%p], %d)\n", tm_get_symbol_name(symbol_id), addr, val);
    *(int32_t*)addr = val;
}

extern "C" void tm_write_i8(void* addr, int64_t val, uint32_t symbol_id) {
    printf("tm_write_i8(%s[%p], %lld)\n", tm_get_symbol_name(symbol_id), addr, val);
    *(int64_t*)addr = val;
}

extern "C" void tm_write_f4(void* addr, float val, uint32_t symbol_id) {
    printf("tm_write_f4(%s[%p], %f)\n", tm_get_symbol_name(symbol_id), addr, val);
    *(float*)addr = val;
}

extern "C" void tm_write_f8(void* addr, double val, uint32_t symbol_id) {
    printf("tm_write_f8(%s[%p], %lf)\n", tm_get_symbol_name(symbol_id), addr, val);
    *(double*)addr = val;
}

extern "C" void tm_write_ptr(void* addr, void* val, uint32_t symbol_id) {
    printf("tm_write_ptr(%s[%p], %p)\n", tm_get_symbol_name(symbol_id), addr, val);
    *(void**)addr = val;
}

extern "C" void tm_write_z(void* dst, void* src, size_t sz, uint32_t symbol_id) {
    assert(sz < TM_BUFFER_SIZE);
    memcpy(dst, src, sz);
    printf("tm_write_z(%s[%p], %p, %zu)\n", tm_get_symbol_name(symbol_id), dst, src, sz);
}

extern "C" void tm_memset(void* dst, uint8_t value, size_t sz, uint32_t symbol_id) {
    assert(sz < TM_BUFFER_SIZE);
    memset(dst, value, sz);
    printf("tm_memset(%s[%p], %u, %zu)\n", tm_get_symbol_name(symbol_id), dst, value, sz);
}

extern "C" void consume_ptr(volatile void* ptr) {
    (void)ptr;
}
