/// Test: queue-based transaction execution
/// Verifies that tm_enqueue + tm_wait_prev_tx are generated by the plugin.
/// The test compiles to IR; we check the .instr.ll for expected call patterns.

// The plugin generates C-linkage calls to tm_wait_prev_tx
extern "C" void tm_wait_prev_tx(void);

__attribute__((noinline, annotate("transaction")))
void increment(int delta) {
    static int shared = 0;
    shared += delta;
}

__attribute__((noinline, annotate("async_transaction")))
void async_increment(int delta) {
    static int shared = 0;
    shared += delta;
}

int main() {
    // Should be replaced with tm_enqueue + tm_wait_prev_tx
    increment(42);

    // Should be replaced with tm_enqueue only (async)
    async_increment(58);

    // Explicit wait for the async TX
    tm_wait_prev_tx();
    return 0;
}
