pub mod event;
pub mod queue;
pub mod engine;
pub mod trace;
pub mod lp;
pub mod memory;
pub mod checker;
pub mod rng;
pub mod ser;
pub mod tm_model;
pub mod bank_sim;
pub mod sim_engine;
pub mod verifier;
pub mod backend;
pub mod calibration;
pub mod cost_model;
pub mod deadlock;
pub mod checkpoint;
pub mod machine_profile;
pub mod computation_profile;
pub mod live_app;

use clap::Parser;

#[derive(Parser, Debug)]
#[command(name = "tm-des", about = "TM Discrete Event Simulator")]
pub struct Cli {
    /// Path to trace file (JSONL). Use '-' for stdin.
    #[arg(short, long, default_value = "-")]
    pub trace: String,

    /// Path to machine profile JSON (hardware characteristics).
    /// Generated by the profiling script on the target machine.
    #[arg(long)]
    pub machine_profile: Option<String>,

    /// Path to calibration JSON (raw profiling data).
    /// Converted to a machine profile via calibration_to_machine_profile().
    /// Overrides --machine-profile if both are provided.
    #[arg(long)]
    pub calibration: Option<String>,

    /// Backend to simulate (affects cost formulas).
    #[arg(long, default_value = "default")]
    pub backend: String,

    /// Clock mode: "timestamp" (trace timestamps) or "cost" (estimated cycles).
    #[arg(long, default_value = "timestamp")]
    pub clock_mode: String,

    /// Output file for processed events (default: tm-des.output.jsonl).
    #[arg(short, long)]
    pub output: Option<String>,

    /// Restore from checkpoint file instead of starting fresh.
    #[arg(long)]
    pub checkpoint: Option<String>,

    /// Save checkpoint every N events (0 = disabled).
    #[arg(long, default_value = "10000")]
    pub checkpoint_every: u64,

    /// Stop after processing M events (0 = unlimited).
    #[arg(long, default_value = "0")]
    pub max_events: u64,

    /// Retries before livelock warning.
    #[arg(long, default_value = "1000")]
    pub livelock_threshold: u32,

    /// Retry cost multiplier (P3). Applied to abort cost for synthetic conflicts.
    /// 0 = disabled (no retry penalty). Default 3x accounts for TX body re-execution.
    #[arg(long, default_value = "3")]
    pub retry_cost_multiplier: u64,

    /// Effective CPU frequency in GHz (P4). Overrides machine_profile.freq_ghz
    /// for cycles→time conversion. Useful when turbo boost is active.
    #[arg(long)]
    pub effective_freq: Option<f64>,
}
