// ── Workload Profile ────────────────────────────────────────
// Workload characteristics loaded from a JSON file.  This
// describes the expected behavior of a benchmark or application
// independently of the hardware it runs on.
//
// The workload profile can come from two sources:
//   1. Compiler plugin: the LLVM pass instruments TM globals
//      and can collect workload statistics during compilation.
//   2. Trace analysis: run the instrumented program once and
//      analyze the trace to produce a workload profile.
//
// The simulator uses the workload profile to:
//   - Calibrate synthetic workload generation (DES mode)
//   - Validate real traces (do they match expected profiles?)
//   - Predict scalability across different hardware

use std::path::Path;

/// Distribution type for a workload metric.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub enum Distribution {
    Uniform,
    Normal { mean: f64, std: f64 },
    Poisson { lambda: f64 },
    Empirical { buckets: Vec<(f64, f64)> },
}

/// Read-set characteristics.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ReadSetProfile {
    /// Average read-set size per transaction.
    pub mean: f64,
    /// Median read-set size.
    pub median: f64,
    /// P90 read-set size.
    pub p90: f64,
    /// P99 read-set size.
    pub p99: f64,
    /// Distribution approximation.
    pub distribution: Distribution,
}

/// Write-set characteristics.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct WriteSetProfile {
    /// Average write-set size per transaction.
    pub mean: f64,
    /// Median write-set size.
    pub median: f64,
    /// P90 write-set size.
    pub p90: f64,
    /// P99 write-set size.
    pub p99: f64,
    /// Distribution approximation.
    pub distribution: Distribution,
}

/// Address access pattern — describes how transactions access memory.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct AccessPattern {
    /// Fraction of accesses that are read vs write (0.0 = all writes, 1.0 = all reads).
    pub read_ratio: f64,
    /// Locality: probability that an access hits an already-accessed cache line.
    pub locality: f64,
    /// Cache-line stride between consecutive accesses (in lines).
    pub stride: f64,
}

/// Contention characteristics.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ContentionProfile {
    /// Overall abort rate (aborts / total transactions).
    pub abort_rate: f64,
    /// Fraction of aborts due to true conflicts.
    pub conflict_abort_ratio: f64,
    /// Fraction of aborts due to capacity overflow.
    pub capacity_abort_ratio: f64,
    /// Contention level classification.
    pub level: ContentionLevel,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub enum ContentionLevel {
    None,
    Low,
    Medium,
    High,
    Extreme,
}

/// Per-backend workload characteristics.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct BackendWorkloadProfile {
    /// Backend name.
    pub backend: String,
    /// Number of validation failures per committed transaction.
    pub validations_per_commit: f64,
    /// Number of lock contentions per committed transaction.
    pub contentions_per_commit: f64,
    /// Snapshot extensions per transaction.
    pub extensions_per_tx: f64,
}

/// Complete workload profile for a benchmark.
///
/// Generated by the compiler plugin (LLVM pass) or by analyzing
/// a trace file.  Describes what the benchmark *does* without
/// reference to the specific hardware it runs on.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct WorkloadProfile {
    /// Benchmark name.
    pub benchmark: String,
    /// Number of threads.
    pub threads: u32,
    /// Duration in seconds (0 if unknown).
    pub duration_s: f64,
    /// Total number of transactions executed.
    pub total_transactions: u64,
    /// Read-set characteristics.
    pub read_set: ReadSetProfile,
    /// Write-set characteristics.
    pub write_set: WriteSetProfile,
    /// Memory access pattern.
    pub access_pattern: AccessPattern,
    /// Contention characteristics.
    pub contention: ContentionProfile,
    /// Per-backend workload characteristics.
    pub backends: Vec<BackendWorkloadProfile>,
}

impl WorkloadProfile {
    /// Load from a JSON file.
    pub fn load(path: &Path) -> Result<Self, String> {
        let data = std::fs::read_to_string(path)
            .map_err(|e| format!("Cannot read workload profile {}: {}", path.display(), e))?;
        let profile: WorkloadProfile = serde_json::from_str(&data)
            .map_err(|e| format!("Cannot parse workload profile {}: {}", path.display(), e))?;
        Ok(profile)
    }

    /// Save to a JSON file.
    pub fn save(&self, path: &Path) -> Result<(), String> {
        let data = serde_json::to_string_pretty(self)
            .map_err(|e| format!("Cannot serialize workload profile: {}", e))?;
        std::fs::write(path, data)
            .map_err(|e| format!("Cannot write workload profile {}: {}", path.display(), e))?;
        Ok(())
    }

    /// Get per-backend profile.
    pub fn backend(&self, name: &str) -> Option<BackendWorkloadProfile> {
        self.backends.iter().find(|b| b.backend == name).cloned()
    }

    /// Estimate expected transaction execution time (in cycles) for a given backend
    /// using the workload profile and machine characteristics.
    pub fn estimated_cycles_per_tx(
        &self,
        machine: &crate::machine_profile::MachineProfile,
        backend_name: &str,
    ) -> f64 {
        let bk = machine.backend(backend_name);
        let reads = self.read_set.mean;
        let writes = self.write_set.mean;

        let read_cost = reads * (machine.tsx.read_l1_cycles + bk.read_overhead);
        let write_cost = writes * (machine.tsx.write_l1_cycles + bk.write_overhead);
        let tx_cost = bk.begin_overhead + bk.commit_overhead;
        let abort_cost = self.contention.abort_rate * bk.abort_overhead;
        let validation_cost = reads * self.contention.abort_rate * bk.validation_entry_cost;

        read_cost + write_cost + tx_cost + abort_cost + validation_cost
    }
}
