/**
 * Persistent Runtime for LLVM TM Plugin
 *
 * This runtime persists TM global variables to disk between runs.
 * Uses the symbol table to know which variables to save/load.
 *
 * Provides function-pointer (DATA) symbols for all hooks the LLVM
 * pass loads from (load ptr, ptr @hook_name → indirect call).
 */

#include <csetjmp>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <mutex>
#include <sys/stat.h>
#include <unistd.h>

#define TM_BUFFER_SIZE 1024

// Per-thread TM state struct — must match the LLVM pass's offset constants:
//   COUNTER_OFFSET = 0  (nested_call_counter)
//   JMPRET_OFFSET  = 4  (longjmp_ret)
struct TMThreadState {
    int32_t nested_call_counter;
    int32_t longjmp_ret;
};

// Thread-local state
static thread_local TMThreadState g_tm_state{0, 0};
__thread unsigned char tm_jmpbuf[256];
__thread uint8_t is_tm_init_thread_ready = 0;
thread_local uint8_t tm_buffer[TM_BUFFER_SIZE] = {0};

static const char *PERSIST_FILE = "/tmp/tm_persistent_state.bin";

// Symbol table declarations (generated by plugin)
extern const char *tm_symbol_names[];
extern const void *tm_symbol_addresses[];
extern const uint32_t tm_symbol_count;

// ═══════════════════════════════════════════════════════════════
// Hook implementations (static — internal linkage)
// ═══════════════════════════════════════════════════════════════

static TMThreadState *impl_get_thread_state() {
    return &g_tm_state;
}

static void impl_init()
{
	printf("tm_init\n");
	fflush(stdout);

	// Try to load persisted state from file
	std::ifstream ifs(PERSIST_FILE, std::ios::binary);
	if (ifs.is_open()) {
		printf("Persistent runtime: loading state from %s\n", PERSIST_FILE);

		uint32_t count = 0;
		ifs.read(reinterpret_cast<char *>(&count), sizeof(count));

		printf("Persistent runtime: found %u symbols in file\n", count);

		for (uint32_t i = 0; i < count && i < tm_symbol_count; i++) {
			char name[256] = {0};
			uint64_t saved_addr = 0;

			// Read name
			uint32_t name_len = 0;
			ifs.read(reinterpret_cast<char *>(&name_len), sizeof(name_len));
			if (name_len > 0 && name_len < 256) {
				ifs.read(name, name_len);
			}

			// Find the current address of this symbol by name
			const void *current_addr = nullptr;
			for (uint32_t j = 0; j < tm_symbol_count; j++) {
				if (strcmp(name, tm_symbol_names[j]) == 0) {
					current_addr = tm_symbol_addresses[j];
					break;
				}
			}

			if (current_addr != nullptr) {
				// Copy value to the current address
				uint64_t val = 0;
				ifs.read(reinterpret_cast<char *>(&val), sizeof(val));
				memcpy(const_cast<void *>(current_addr), &val, sizeof(val));
				printf("Persistent runtime: restored %s at %p = 0x%llx\n",
				       name,
				       current_addr,
				       (unsigned long long)val);
			} else {
				printf("Persistent runtime: symbol %s not found in current run\n", name);
			}
		}

		ifs.close();
		printf("Persistent runtime: state loaded successfully\n");
	} else {
		printf("Persistent runtime: no persist file found, starting fresh\n");
	}

	fflush(stdout);
}

static void impl_exit()
{
	printf("tm_exit\n");
	fflush(stdout);

	// Persist state to file
	std::ofstream ofs(PERSIST_FILE, std::ios::binary);
	if (ofs.is_open()) {
		printf("Persistent runtime: saving state to %s\n", PERSIST_FILE);

		// Write symbol count
		ofs.write(reinterpret_cast<const char *>(&tm_symbol_count),
		          sizeof(tm_symbol_count));

		for (uint32_t i = 0; i < tm_symbol_count; i++) {
			const char *name = tm_symbol_names[i];
			const void *addr = tm_symbol_addresses[i];

			// Write name
			uint32_t name_len = strlen(name) + 1;
			ofs.write(reinterpret_cast<const char *>(&name_len), sizeof(name_len));
			ofs.write(name, name_len);

			// Write value (assume 8 bytes max for simplicity)
			uint64_t val = 0;
			if (addr != nullptr) {
				memcpy(&val, addr, sizeof(val));
			}
			ofs.write(reinterpret_cast<const char *>(&val), sizeof(val));

			printf("Persistent runtime: saved %s = 0x%llx\n",
			       name,
			       (unsigned long long)val);
		}

		ofs.close();
		printf("Persistent runtime: state saved successfully\n");
	} else {
		printf("Persistent runtime: ERROR could not open %s for writing\n", PERSIST_FILE);
	}

	fflush(stdout);
}

static void impl_init_thread()
{
	if (is_tm_init_thread_ready == 0) {
		printf("tm_init_thread\n");
		fflush(stdout);
		is_tm_init_thread_ready = 1;
	}
}

static void impl_exit_thread()
{
	if (is_tm_init_thread_ready == 1) {
		printf("tm_exit_thread\n");
		fflush(stdout);
		is_tm_init_thread_ready = 0;
	}
}

static std::recursive_mutex g_serialize_mutex;

static void impl_serialize_lock() { g_serialize_mutex.lock(); }
static void impl_serialize_unlock() { g_serialize_mutex.unlock(); }

static void impl_set_jmpbuf(void *buf) { }
static sigjmp_buf *impl_get_env() { return (sigjmp_buf *)tm_jmpbuf; }

static void impl_begin()
{
	printf("tm_nested_call_counter=%d  --  ", g_tm_state.nested_call_counter);
	if (g_tm_state.nested_call_counter == 1) {
		printf("tm_begin outer\n");
	} else {
		printf("tm_begin nested %d\n", g_tm_state.nested_call_counter);
	}
	fflush(stdout);
}

static void impl_end()
{
	printf("tm_nested_call_counter=%d  --  ", g_tm_state.nested_call_counter);
	if (g_tm_state.nested_call_counter == 1) {
		printf("tm_end outer\n");
	} else {
		printf("tm_end nested %d\n", g_tm_state.nested_call_counter);
	}
	fflush(stdout);
}

// Read functions
static int8_t  impl_read_i1(void  *a) { int8_t  v = *(int8_t*)a;  printf("tm_read_i1\n"); return v; }
static int16_t impl_read_i2(void  *a) { int16_t v = *(int16_t*)a; printf("tm_read_i2\n"); return v; }
static int32_t impl_read_i4(void  *a) { int32_t v = *(int32_t*)a; printf("tm_read_i4\n"); return v; }
static int64_t impl_read_i8(void  *a) { int64_t v = *(int64_t*)a; printf("tm_read_i8\n"); return v; }
static float   impl_read_f4(void  *a) { float   v = *(float*)a;   printf("tm_read_f4\n"); return v; }
static double  impl_read_f8(void  *a) { double  v = *(double*)a;  printf("tm_read_f8\n"); return v; }
static void   *impl_read_ptr(void **a) { void   *v = *a;           printf("tm_read_ptr\n"); return v; }

// Write functions
static void impl_write_i1(void  *a, int8_t  v) { printf("tm_write_i1\n");  *(int8_t*)a  = v; }
static void impl_write_i2(void  *a, int16_t v) { printf("tm_write_i2\n");  *(int16_t*)a = v; }
static void impl_write_i4(void  *a, int32_t v) { printf("tm_write_i4\n");  *(int32_t*)a = v; }
static void impl_write_i8(void  *a, int64_t v) { printf("tm_write_i8\n");  *(int64_t*)a = v; }
static void impl_write_f4(void  *a, float   v) { printf("tm_write_f4\n");  *(float*)a   = v; }
static void impl_write_f8(void  *a, double  v) { printf("tm_write_f8\n");  *(double*)a  = v; }
static void impl_write_ptr(void **a, void   *v) { printf("tm_write_ptr\n"); *a = v; }

static void impl_memset(void *dst, uint8_t val, size_t sz) { memset(dst, val, sz); }

// ═══════════════════════════════════════════════════════════════
// Hook function-pointer globals — the LLVM pass loads from these
// DATA symbols to get function pointers for indirect calls.
// ═══════════════════════════════════════════════════════════════

extern "C" {

void     (*tm_init)()                          = impl_init;
void     (*tm_exit)()                          = impl_exit;
void     (*tm_init_thread)()                   = impl_init_thread;
void     (*tm_exit_thread)()                   = impl_exit_thread;
void     (*tm_begin)()                         = (void(*)())impl_begin;
void     (*tm_end)()                           = (void(*)())impl_end;
void     (*tm_set_jmpbuf)(void*)               = impl_set_jmpbuf;
void    *(*tm_get_env)()                       = (void*(*)())impl_get_env;
void     (*tm_serialize_lock)()                = impl_serialize_lock;
void     (*tm_serialize_unlock)()              = impl_serialize_unlock;
void     (*tm_memset)(void*, uint8_t, size_t)  = impl_memset;

void    *(*tm_malloc)(size_t)               = (void*(*)(size_t))nullptr;
void    *(*tm_calloc)(size_t, size_t)       = (void*(*)(size_t,size_t))nullptr;
void    *(*tm_realloc)(void*, size_t)       = (void*(*)(void*,size_t))nullptr;
void     (*tm_free)(void*)                  = (void(*)(void*))nullptr;
uint8_t  (*tm_read_i1)(uint8_t*)            = (uint8_t(*)(uint8_t*))impl_read_i1;
uint16_t (*tm_read_i2)(uint16_t*)           = (uint16_t(*)(uint16_t*))impl_read_i2;
uint32_t (*tm_read_i4)(uint32_t*)           = (uint32_t(*)(uint32_t*))impl_read_i4;
uint64_t (*tm_read_i8)(uint64_t*)           = (uint64_t(*)(uint64_t*))impl_read_i8;
float    (*tm_read_f4)(float*)              = (float(*)(float*))impl_read_f4;
double   (*tm_read_f8)(double*)             = (double(*)(double*))impl_read_f8;
void    *(*tm_read_ptr)(void**)             = (void*(*)(void**))impl_read_ptr;
void     (*tm_write_i1)(uint8_t*, uint8_t)  = (void(*)(uint8_t*,uint8_t))impl_write_i1;
void     (*tm_write_i2)(uint16_t*, uint16_t)= (void(*)(uint16_t*,uint16_t))impl_write_i2;
void     (*tm_write_i4)(uint32_t*, uint32_t)= (void(*)(uint32_t*,uint32_t))impl_write_i4;
void     (*tm_write_i8)(uint64_t*, int64_t) = (void(*)(uint64_t*,int64_t))impl_write_i8;
void     (*tm_write_f4)(float*, float)      = (void(*)(float*,float))impl_write_f4;
void     (*tm_write_f8)(double*, double)    = (void(*)(double*,double))impl_write_f8;
void     (*tm_write_ptr)(void**, void*)      = (void(*)(void**,void*))impl_write_ptr;
void     (*tm_get_thread_state)() = (void(*)())impl_get_thread_state;

// ── Functions called directly (not through hook pointers) ───
// These are called directly by the LLVM pass preamble, so they
// must be actual function symbols (TEXT), not function-pointer
// globals.

void tm_flush_deferred_frees() {}
void tm_clear_deferred_frees() {}

int tm_setjmp() { return sigsetjmp(*(sigjmp_buf *)tm_jmpbuf, 0); }

void tm_longjmp(int val) { longjmp(*(sigjmp_buf *)tm_jmpbuf, val); }

void consume_ptr(volatile void *ptr) { (void)ptr; }

} // extern "C"

// tm_sigsetjmp hook: the LLVM pass declares @tm_sigsetjmp as a DATA ptr.
// We must provide a DATA symbol (function pointer) containing the address
// of the real sigsetjmp implementation — NOT the implementation itself.
// On glibc, sigsetjmp is a macro expanding to __sigsetjmp(env, savemask);
// taking its address requires the underlying function name.
#if defined(__APPLE__)
int (*tm_sigsetjmp)(void*, int) = (int(*)(void*, int))sigsetjmp;
#else
int (*tm_sigsetjmp)(void*, int) = (int(*)(void*, int))__sigsetjmp;
#endif
