/**
 * Persistent Runtime for LLVM TM Plugin
 *
 * This runtime persists TM global variables to disk between runs.
 * Uses the symbol table to know which variables to save/load.
 */

#include <csetjmp>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <mutex>
#include <sys/stat.h>
#include <unistd.h>

#define TM_BUFFER_SIZE 1024

// Thread-local state
__thread int32_t tm_nested_call_counter;
__thread unsigned char tm_jmpbuf[256];
__thread int32_t tm_longjmp_ret;
__thread uint8_t is_tm_init_thread_ready = 0;
thread_local uint8_t tm_buffer[TM_BUFFER_SIZE] = {0};

static const char *PERSIST_FILE = "/tmp/tm_persistent_state.bin";

// Symbol table declarations (generated by plugin)
extern const char *tm_symbol_names[];
extern const void *tm_symbol_addresses[];
extern const uint32_t tm_symbol_count;

extern "C" {

void tm_init()
{
	printf("tm_init\n");
	fflush(stdout);

	// Try to load persisted state from file
	std::ifstream ifs(PERSIST_FILE, std::ios::binary);
	if (ifs.is_open()) {
		printf("Persistent runtime: loading state from %s\n", PERSIST_FILE);

		uint32_t count = 0;
		ifs.read(reinterpret_cast<char *>(&count), sizeof(count));

		printf("Persistent runtime: found %u symbols in file\n", count);

		for (uint32_t i = 0; i < count && i < tm_symbol_count; i++) {
			char name[256] = {0};
			uint64_t saved_addr = 0;

			// Read name
			uint32_t name_len = 0;
			ifs.read(reinterpret_cast<char *>(&name_len), sizeof(name_len));
			if (name_len > 0 && name_len < 256) {
				ifs.read(name, name_len);
			}

			// Read saved value
			uint64_t val = 0;
			ifs.read(reinterpret_cast<char *>(&val), sizeof(val));

			// Find the current address of this symbol by name
			const void *current_addr = nullptr;
			for (uint32_t j = 0; j < tm_symbol_count; j++) {
				if (strcmp(name, tm_symbol_names[j]) == 0) {
					current_addr = tm_symbol_addresses[j];
					break;
				}
			}

			if (current_addr != nullptr) {
				// Copy value to the current address
				memcpy(const_cast<void *>(current_addr), &val, sizeof(val));
				printf("Persistent runtime: restored %s at %p = 0x%llx\n",
				       name,
				       current_addr,
				       (unsigned long long)val);
			} else {
				printf("Persistent runtime: symbol %s not found in current run\n", name);
			}
		}

		ifs.close();
		printf("Persistent runtime: state loaded successfully\n");
	} else {
		printf("Persistent runtime: no persist file found, starting fresh\n");
	}

	fflush(stdout);
}

void tm_exit()
{
	printf("tm_exit\n");
	fflush(stdout);

	// Persist state to file
	std::ofstream ofs(PERSIST_FILE, std::ios::binary);
	if (ofs.is_open()) {
		printf("Persistent runtime: saving state to %s\n", PERSIST_FILE);

		// Write symbol count
		ofs.write(reinterpret_cast<const char *>(&tm_symbol_count),
		          sizeof(tm_symbol_count));

		for (uint32_t i = 0; i < tm_symbol_count; i++) {
			const char *name = tm_symbol_names[i];
			const void *addr = tm_symbol_addresses[i];

			// Write name
			uint32_t name_len = strlen(name) + 1;
			ofs.write(reinterpret_cast<const char *>(&name_len), sizeof(name_len));
			ofs.write(name, name_len);

			// Write value (assume 8 bytes max for simplicity)
			uint64_t val = 0;
			if (addr != nullptr) {
				memcpy(&val, addr, sizeof(val));
			}
			ofs.write(reinterpret_cast<const char *>(&val), sizeof(val));

			printf("Persistent runtime: saved %s = 0x%llx\n",
			       name,
			       (unsigned long long)val);
		}

		ofs.close();
		printf("Persistent runtime: state saved successfully\n");
	} else {
		printf("Persistent runtime: ERROR could not open %s for writing\n", PERSIST_FILE);
	}

	fflush(stdout);
}

void tm_init_thread()
{
	if (is_tm_init_thread_ready == 0) {
		printf("tm_init_thread\n");
		fflush(stdout);
		is_tm_init_thread_ready = 1;
	}
}

void tm_exit_thread()
{
	if (is_tm_init_thread_ready == 1) {
		printf("tm_exit_thread\n");
		fflush(stdout);
		is_tm_init_thread_ready = 0;
	}
}

static std::recursive_mutex g_serialize_mutex;

void tm_serialize_lock()
{
	g_serialize_mutex.lock();
}

void tm_serialize_unlock()
{
	g_serialize_mutex.unlock();
}

// int tm_setjmp() { return sigsetjmp(*(sigjmp_buf *)tm_jmpbuf, 0); }

void tm_set_jmpbuf(void *buf) { }

void tm_begin()
{
	printf("tm_nested_call_counter=%d  --  ", tm_nested_call_counter);
	if (tm_nested_call_counter == 1) {
		printf("tm_begin outer\n");
	} else {
		printf("tm_begin nested %d\n", tm_nested_call_counter);
	}
	fflush(stdout);
}

void tm_end()
{
	printf("tm_nested_call_counter=%d  --  ", tm_nested_call_counter);
	if (tm_nested_call_counter == 1) {
		printf("tm_end outer\n");
	} else {
		printf("tm_end nested %d\n", tm_nested_call_counter);
	}
	fflush(stdout);
}

// Read functions
int8_t tm_read_i1(void *addr)
{
	int8_t val = *(int8_t *)addr;
	printf("tm_read_i1\n");
	return val;
}
int16_t tm_read_i2(void *addr)
{
	int16_t val = *(int16_t *)addr;
	printf("tm_read_i2\n");
	return val;
}
int32_t tm_read_i4(void *addr)
{
	int32_t val = *(int32_t *)addr;
	printf("tm_read_i4\n");
	return val;
}
int64_t tm_read_i8(void *addr)
{
	int64_t val = *(int64_t *)addr;
	printf("tm_read_i8\n");
	return val;
}
float tm_read_f4(void *addr)
{
	float val = *(float *)addr;
	printf("tm_read_f4\n");
	return val;
}
double tm_read_f8(void *addr)
{
	double val = *(double *)addr;
	printf("tm_read_f8\n");
	return val;
}
void *tm_read_ptr(void *addr)
{
	void *val = *(void **)addr;
	printf("tm_read_ptr\n");
	return val;
}
void *tm_read_z(void *src, size_t sz)
{
	memcpy(tm_buffer, src, sz);
	return tm_buffer;
}

// Write functions
void tm_write_i1(void *addr, int8_t val)
{
	printf("tm_write_i1\n");
	*(int8_t *)addr = val;
}
void tm_write_i2(void *addr, int16_t val)
{
	printf("tm_write_i2\n");
	*(int16_t *)addr = val;
}
void tm_write_i4(void *addr, int32_t val)
{
	printf("tm_write_i4\n");
	*(int32_t *)addr = val;
}
void tm_write_i8(void *addr, int64_t val)
{
	printf("tm_write_i8\n");
	*(int64_t *)addr = val;
}
void tm_write_f4(void *addr, float val)
{
	printf("tm_write_f4\n");
	*(float *)addr = val;
}
void tm_write_f8(void *addr, double val)
{
	printf("tm_write_f8\n");
	*(double *)addr = val;
}
void tm_write_ptr(void *addr, void *val)
{
	printf("tm_write_ptr\n");
	*(void **)addr = val;
}
void tm_write_z(void *dst, void *src, size_t sz) { memcpy(dst, src, sz); }

void tm_memset(void *dst, uint8_t val, size_t sz) { memset(dst, val, sz); }

void consume_ptr(volatile void *ptr) { (void)ptr; }

} // extern "C"
