[package]
name = "benchmarks"
version = "0.1.0"
edition = "2021"

[lib]
name = "benchmarks"
path = "src/lib.rs"

[[bin]]
name = "datastructures"
path = "src/bin/datastructures.rs"

[[bin]]
name = "stamp_vacation"
path = "src/cli/stamp_vacation.rs"

[[bin]]
name = "stamp_kmeans"
path = "src/cli/stamp_kmeans.rs"

[[bin]]
name = "stamp_genome"
path = "src/cli/stamp_genome.rs"

[[bin]]
name = "stamp_intruder"
path = "src/cli/stamp_intruder.rs"

[[bin]]
name = "stamp_labyrinth"
path = "src/cli/stamp_labyrinth.rs"

[[bin]]
name = "stamp_ssca2"
path = "src/cli/stamp_ssca2.rs"

[[bin]]
name = "stamp_bayes"
path = "src/cli/stamp_bayes.rs"

[[bin]]
name = "stamp_yada"
path = "src/cli/stamp_yada.rs"

[features]
default = ["wbctl"]
wbctl = ["tm/wbctl"]
wbetl = ["tm/wbetl"]
wt    = ["tm/wt"]
norec   = ["tm/norec"]
tl2     = ["tm/tl2"]
swisstm = ["tm/swisstm"]
dudetm  = ["tm/dudetm"]
tsxsgl  = ["tm/tsxsgl"]
nvhtm   = ["tm/nvhtm"]
spht    = ["tm/spht"]
leftright = ["tm/leftright"]
leftright-single = ["tm/leftright-single"]
romulus   = ["tm/romulus"]
xtm       = ["tm/xtm"]

[dependencies]
tm = { path = "../tm", default-features = false }
containers = { path = "../containers" }
fastrand = "2"
